#!/usr/bin/env python3
"""Prepare the Open Duck Playground soft-prior training patch.

Default mode is read-only: it validates the expected Joystick/runner insertion
points and prints unified diffs. Pass --apply to modify the sibling Playground
checkout. All inserted behavior is default-off.
"""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PLAYGROUND = ROOT.parent / "Open_Duck_Playground"
JOYSTICK_REL = Path("playground/open_duck_mini_v2/joystick.py")
RUNNER_REL = Path("playground/open_duck_mini_v2/runner.py")


SOFT_PRIOR_CONFIG = '''        soft_prior=config_dict.create(
            enable=False,
            joint_indices=[2, 3, 4, 11, 12, 13],
            action_mean=[],
            period=50,
            phase_source="imitation_i",
            huber_delta=0.05,
        ),
'''


SOFT_PRIOR_INFO = '''            "soft_prior_cost": jp.zeros(()),
            "soft_prior_phase": jp.zeros((), dtype=jp.int32),
'''


SOFT_PRIOR_HELPER = '''
    def _get_soft_prior_cost(
        self, action: jax.Array, info: dict[str, Any]
    ) -> tuple[jax.Array, jax.Array]:
        """Return default-off pitch-chain soft-prior cost and phase index."""
        cfg = self._config.soft_prior
        if not cfg.enable or len(cfg.action_mean) == 0:
            return jp.zeros(()), jp.zeros((), dtype=jp.int32)

        action_mean = jp.asarray(cfg.action_mean, dtype=action.dtype)
        joint_indices = jp.asarray(cfg.joint_indices, dtype=jp.int32)
        period = action_mean.shape[0]
        if cfg.phase_source == "step":
            phase = jp.mod(info["step"], period).astype(jp.int32)
        else:
            phase = jp.mod(info["imitation_i"], period).astype(jp.int32)
        prior_action = action_mean[phase]
        action_subset = jp.take(action, joint_indices)
        cost = jp.mean(pseudo_huber_cost(action_subset - prior_action, cfg.huber_delta))
        return cost, phase

'''


RUNNER_CONFIG_BLOCK = '''        if args.enable_soft_prior:
            if not hasattr(config, "soft_prior"):
                raise ValueError("Selected env config does not expose soft_prior")
            config.soft_prior.enable = True
            config.soft_prior.phase_source = args.soft_prior_phase_source
            config.soft_prior.huber_delta = args.soft_prior_huber_delta
            if args.soft_prior_config_json is None:
                raise ValueError("--enable_soft_prior requires --soft_prior_config_json")
            payload = json.loads(Path(args.soft_prior_config_json).read_text())
            prior = payload.get("prior") or {}
            action_mean = prior.get("action_mean") or []
            joint_indices = prior.get("joint_indices") or []
            if not action_mean or not joint_indices:
                raise ValueError("soft-prior config missing prior.action_mean/joint_indices")
            config.soft_prior.action_mean = action_mean
            config.soft_prior.joint_indices = joint_indices
            config.soft_prior.period = int(prior.get("window_len") or len(action_mean))
            config.reward_config.scales.soft_prior = args.soft_prior_scale

'''


RUNNER_ARG_BLOCK = '''    parser.add_argument(
        "--enable_soft_prior",
        action="store_true",
        help="Enable default-off pitch-chain soft-prior auxiliary cost.",
    )
    parser.add_argument(
        "--soft_prior_config_json",
        type=str,
        default=None,
        help="Compact soft-prior config generated by build_soft_prior_fragment_config.py.",
    )
    parser.add_argument(
        "--soft_prior_scale",
        type=float,
        default=-0.05,
        help="Reward scale for soft_prior cost. Use a negative value to penalize.",
    )
    parser.add_argument("--soft_prior_huber_delta", type=float, default=0.05)
    parser.add_argument(
        "--soft_prior_phase_source",
        choices=["imitation_i", "step"],
        default="imitation_i",
    )
'''


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise ValueError(f"expected one {label} insertion point, found {count}")
    return text.replace(old, new, 1)


def patch_joystick(text: str) -> str:
    if "soft_prior=config_dict.create(" in text:
        return text
    text = replace_once(
        text,
        "        reward_config=config_dict.create(\n",
        SOFT_PRIOR_CONFIG + "        reward_config=config_dict.create(\n",
        "soft_prior config",
    )
    text = replace_once(
        text,
        "                actuator_tracking=0.0,\n",
        "                actuator_tracking=0.0,\n                soft_prior=0.0,\n",
        "soft_prior reward scale",
    )
    text = replace_once(
        text,
        '            "target_velocity_cost": jp.zeros(()),\n',
        '            "target_velocity_cost": jp.zeros(()),\n' + SOFT_PRIOR_INFO,
        "soft_prior info",
    )
    text = replace_once(
        text,
        '        metrics["diagnostic/command_progress_ratio"] = jp.zeros(())\n',
        (
            '        metrics["diagnostic/soft_prior_cost"] = jp.zeros(())\n'
            '        metrics["diagnostic/soft_prior_phase"] = jp.zeros(())\n'
            '        metrics["diagnostic/command_progress_ratio"] = jp.zeros(())\n'
        ),
        "soft_prior reset metrics",
    )
    text = replace_once(
        text,
        "    def _get_reward(\n",
        SOFT_PRIOR_HELPER + "    def _get_reward(\n",
        "soft_prior helper",
    )
    text = replace_once(
        text,
        "        del metrics  # Unused.\n\n        ret = {\n",
        (
            "        del metrics  # Unused.\n\n"
            "        soft_prior_cost, soft_prior_phase = self._get_soft_prior_cost(action, info)\n"
            '        info["soft_prior_cost"] = soft_prior_cost\n'
            '        info["soft_prior_phase"] = soft_prior_phase\n\n'
            "        ret = {\n"
        ),
        "soft_prior reward computation",
    )
    text = replace_once(
        text,
        '''            "actuator_tracking": info["actuator_bridge_tracking_cost"],
            "alive": reward_alive(),
''',
        '''            "actuator_tracking": info["actuator_bridge_tracking_cost"],
            "soft_prior": info["soft_prior_cost"],
            "alive": reward_alive(),
''',
        "soft_prior reward term",
    )
    text = replace_once(
        text,
        '''        state.metrics["diagnostic/command_progress_ratio"] = state.info[
            "command_progress_ratio"
        ]
''',
        '''        state.metrics["diagnostic/soft_prior_cost"] = state.info["soft_prior_cost"]
        state.metrics["diagnostic/soft_prior_phase"] = state.info[
            "soft_prior_phase"
        ].astype(reward.dtype)
        state.metrics["diagnostic/command_progress_ratio"] = state.info[
            "command_progress_ratio"
        ]
''',
        "soft_prior step metrics",
    )
    return text


def patch_runner(text: str) -> str:
    if "--enable_soft_prior" in text:
        return text
    text = replace_once(
        text,
        "import argparse\n\n",
        "import argparse\nimport json\nfrom pathlib import Path\n\n",
        "runner imports",
    )
    text = replace_once(
        text,
        "        config.reward_config.scales.target_rate = args.target_rate_scale\n",
        RUNNER_CONFIG_BLOCK + "        config.reward_config.scales.target_rate = args.target_rate_scale\n",
        "soft_prior runner config",
    )
    text = replace_once(
        text,
        '''    parser.add_argument(
        "--target_rate_scale",
''',
        RUNNER_ARG_BLOCK
        + '''    parser.add_argument(
        "--target_rate_scale",
''',
        "soft_prior runner args",
    )
    return text


def unified_diff(path: Path, rel: Path, before: str, after: str) -> str:
    return "".join(
        difflib.unified_diff(
            before.splitlines(keepends=True),
            after.splitlines(keepends=True),
            fromfile=f"a/{rel}",
            tofile=f"b/{rel}",
        )
    )


def prepare_file(path: Path, rel: Path, patcher) -> tuple[str, str, str]:
    if not path.exists():
        raise FileNotFoundError(path)
    before = path.read_text()
    after = patcher(before)
    return before, after, unified_diff(path, rel, before, after)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Prepare the default-off Open Duck Playground soft-prior training patch."
    )
    parser.add_argument("--playground-path", default=str(DEFAULT_PLAYGROUND))
    parser.add_argument("--apply", action="store_true", help="modify Playground files")
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate patch generation without applying; default behavior",
    )
    args = parser.parse_args()

    playground = Path(args.playground_path).expanduser().resolve()
    joystick = playground / JOYSTICK_REL
    runner = playground / RUNNER_REL
    try:
        joystick_before, joystick_after, joystick_diff = prepare_file(
            joystick, JOYSTICK_REL, patch_joystick
        )
        runner_before, runner_after, runner_diff = prepare_file(runner, RUNNER_REL, patch_runner)
    except (FileNotFoundError, ValueError) as exc:
        print(f"HOLD_PATCH_CONTEXT_MISMATCH: {exc}", file=sys.stderr)
        return 3

    if joystick_after == joystick_before and runner_after == runner_before:
        print("PASS_ALREADY_PATCHED")
        return 0

    if args.apply:
        joystick.write_text(joystick_after)
        runner.write_text(runner_after)
        print(f"APPLIED {joystick}")
        print(f"APPLIED {runner}")
    else:
        if joystick_diff:
            print(joystick_diff)
        if runner_diff:
            print(runner_diff)
        print("PASS_PATCH_PREPARED", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
